distance-modifier: 1
despawn-delay: 100
resend-delay: 100
different-dimension-delay: 1000

on-join-delay: 100
on-gamemode-delay: 100
on-enable-letters-delay: 100

# CustomModelData da carta comum
cem-letter: 100

# CustomModelData da carta anônima
cem-anonimous-letter: 101

# Variante do pássaro das cartas comuns
pigeon-variant: BLUE

# Variante do pássaro das cartas anônimas
crow-variant: GRAY


blocked-gamemodes: [SPECTATOR]
blocked-worlds: []

